name: Deployment (production)

on:
  workflow_dispatch:
  workflow_call:
  release:
    types:
      - published


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4