name: Security Scan

on:
  workflow_dispatch:
  pull_request:
    branches: [*]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Security Scan
        run: npm audit --omit=dev || exit 1
