name: job_release.yml
on:
  push:
    branches:
      - 'releases/*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build
