name: Linting
on:
  workflow_dispatch:
  pull_request:
    branches: [staging]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint
