name: Validate PR Title

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title against Conventional Commits
        uses: amannn/action-semantic-pull-request@v4
        with:
          types: >
            feat, fix, chore, refactor, perf, test, docs,
            style, ci, build, revert
